#' Create xaringan slides for lectures or workshops
#'
#' @param path A path.
#'
#' @export
create_lecture <- function(path) {
  dir.create(path)
  path <- normalizePath(path, mustWork = TRUE)

  # git ignore
  usethis::use_git_ignore(c("cache/", "*.run.xml"))

  # I put raw data /data-raw
  usethis::use_directory("data-raw")
  # I put cleaned data /data
  usethis::use_directory("data")
  # I put resuable functions to /R
  usethis::use_directory("R")
  # I put my R code to /scripts
  usethis::use_directory("scripts")
  # I put images other than figures generated by R into /img
  usethis::use_directory("img")
  usethis::use_directory("libs")

  # use custom ggplot theme for slides
  r_path <- use_template("slides/theme.R")
  file.copy(r_path, paste0(path, "/R/theme.R"))

  # use my custom xaringan css
  css_path <- use_template("lecture/remark.css")
  file.copy(css_path, paste0(path, "/libs/remark.css"))

  # use custom js
  js_path <- use_template("lecture/collapseoutput.js")
  file.copy(js_path, paste0(path, "/libs/collapseoutput.js"))

  write_template(path, "lecture/index.Rmd", dest = "index.Rmd")
  invisible(TRUE)
}
