#' Create xaringan slides
#'
#' @param path A path.
#'
#' @export
create_slides <- function(path) {
  dir.create(path)
  path <- normalizePath(path, mustWork = TRUE)
  usethis::proj_set(path, force = TRUE)

  # create RStudio project
  usethis::use_rstudio()

  # git ignore
  usethis::use_git_ignore(c("cache/", "*.run.xml"))

  # DESCRIPTION
  usethis::use_description_defaults()
  # I put raw data /data-raw
  usethis::use_directory("data-raw")
  # I put cleaned data /data
  usethis::use_directory("data")
  # I put resuable functions to /R
  usethis::use_directory("R")
  # I put my R code to /scripts
  usethis::use_directory("scripts")
  # I put images other than figures generated by R into /img
  usethis::use_directory("img")
  usethis::use_directory("libs")

  # use custom ggplot theme for slides
  r_path <- use_template("slides/theme.R")
  file.copy(r_path, paste0(path, "/R/theme.R"))

  # use Makefile
  makefile_path <- use_template("slides/Makefile")
  file.copy(makefile_path, paste0(path, "/Makefile"))

  # use deploy.sh
  sh_path <- use_template("slides/deploy.sh")
  file.copy(sh_path, paste0(path, "/deploy.sh"))

  # use my custom xaringan css
  css_path <- use_template("slides/remark.css")
  file.copy(css_path, paste0(path, "/libs/remark.css"))

  # init README.md
  write_template(path, "slides/README.md", dest = "README.md")

  write_template(path, "slides/index.Rmd", dest = "index.Rmd")
  invisible(TRUE)
}

write_template <- function(path, file, dest) {
  temp_path <- system.file("templates", file, package = "wang")
  file_name <- readLines(temp_path)
  repo <- basename(path)
  data <- list(repo = repo)
  done <- whisker::whisker.render(file_name, data)
  usethis::write_over(paste0(path, "/", dest), done, quiet = TRUE)
}

use_template <- function(file) {
  system.file("templates", file, package = "wang")
}
