#' Create xaringan slides
#'
#' @param path A path.
#' @param event A string. Which event.
#' @param date A string. On which day of the event.
#'
#' @export
create_slides <- function(path, event, date) {
  dir.create(path)
  path <- normalizePath(path, mustWork = TRUE)
  usethis::proj_set(path, force = TRUE)

  # create RStudio project
  usethis::use_rstudio()

  # git ignore
  usethis::use_git_ignore(c(".DS_Store", "cache/", "*.run.xml"))

  # I put my R code to /src
  usethis::use_directory("src")
  # I put images other than figures generated by R into /img
  usethis::use_directory("img")

  # use custom ggplot theme for slides
  r_path <- use_template("theme.R")
  file.copy(r_path, paste0(path, "/src/theme.R"))

  # use Makefile
  makefile_path <- use_template("slides-Makefile")
  file.copy(makefile_path, paste0(path, "/Makefile"))

  # use my custom xaringan css
  css_path <- use_template("remark.css")
  file.copy(css_path, paste0(path, "/remark.css"))

  # init README.md
  write_template(path, "README.md", list(event = event, date = date))

  # init index.Rmd
  write_template(path, "index.Rmd", list(date = date))
}

write_template <- function(path, file, data = list()) {
  temp_path <- system.file("templates", file, package = "wang")
  file_name <- readLines(temp_path)
  repo <- basename(path)
  data <- c(data, repo = repo)
  done <- strsplit(whisker::whisker.render(file_name, data), "\n")[[1]]
  write_utf8(paste0(path, "/", file), done)
}

use_template <- function(file) {
  system.file("templates", file, package = "wang")
}

# usethis:::write_utf8
write_utf8 <- function (path, lines) {
  stopifnot(is.character(path))
  stopifnot(is.character(lines))
  con <- file(path, encoding = "utf-8")
  on.exit(close(con), add = TRUE)
  if (length(lines) > 1) {
    lines <- paste0(lines, "\n", collapse = "")
  }
  cat(lines, file = con, sep = "")
  invisible(TRUE)
}
